/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v15.0
processor: MK22FN512xxx12
package_id: MK22FN512VLH12
mcu_data: ksdk2_0
processor_version: 25.06.10
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: 1ab7c269-2fed-4181-936e-230a1d30d0f5
  called_from_default_init: true
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'system'
- type_id: 'system_54b53072540eeeb8f8e9343e71f28176'
- global_system_definitions:
  - user_definitions: ''
  - user_includes: ''
  - global_init: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'gpio_adapter_common'
- type_id: 'gpio_adapter_common'
- global_gpio_adapter_common:
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'uart_cmsis_common'
- type_id: 'uart_cmsis_common'
- global_USART_CMSIS_common: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "peripherals.h"

/***********************************************************************************************************************
 * BOARD_InitPeripherals functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * NVIC initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'NVIC'
- type: 'nvic'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'nvic'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'NVIC'
- config_sets:
  - nvic:
    - interrupt_table:
      - 0: []
      - 1: []
      - 2: []
      - 3: []
      - 4: []
      - 5: []
      - 6: []
      - 7: []
      - 8: []
    - interrupts: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/* Empty initialization function (commented out)
static void NVIC_init(void) {
} */

/***********************************************************************************************************************
 * UART1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'UART1'
- type: 'uart'
- mode: 'freertos'
- custom_name_enabled: 'false'
- type_id: 'uart_2.5.1'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'UART1'
- config_sets:
  - fsl_uart_freertos:
    - uart_rtos_configuration:
      - clockSource: 'BusInterfaceClock'
      - clockSourceFreq: 'GetFreq'
      - baudrate: '115200'
      - parity: 'kUART_ParityDisabled'
      - stopbits: 'kUART_OneStopBit'
      - buffer_size: '32'
    - interrupt_rx_tx:
      - IRQn: 'UART1_RX_TX_IRQn'
      - enable_priority: 'true'
      - priority: '7'
    - interrupt_err:
      - IRQn: 'UART1_ERR_IRQn'
      - enable_priority: 'true'
      - priority: '7'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
uart_rtos_handle_t UART1_rtos_handle;
uart_handle_t UART1_uart_handle;
uint8_t UART1_background_buffer[UART1_BACKGROUND_BUFFER_SIZE];
uart_rtos_config_t UART1_rtos_config = {
  .base = UART1_PERIPHERAL,
  .baudrate = 115200UL,
  .parity = kUART_ParityDisabled,
  .stopbits = kUART_OneStopBit,
  .buffer = UART1_background_buffer,
  .buffer_size = UART1_BACKGROUND_BUFFER_SIZE
};

static void UART1_init(void) {
  /* UART clock source initialization */
  UART1_rtos_config.srcclk = UART1_CLOCK_SOURCE;
  /* UART rtos initialization */
  UART_RTOS_Init(&UART1_rtos_handle, &UART1_uart_handle, &UART1_rtos_config);
  /* Interrupt vector UART1_RX_TX_IRQn priority settings in the NVIC. */
  NVIC_SetPriority(UART1_SERIAL_RX_TX_IRQN, UART1_SERIAL_RX_TX_IRQ_PRIORITY);
  /* Interrupt vector UART1_ERR_IRQn priority settings in the NVIC. */
  NVIC_SetPriority(UART1_SERIAL_ERROR_IRQN, UART1_SERIAL_ERROR_IRQ_PRIORITY);
}

/***********************************************************************************************************************
 * LPUART0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'LPUART0'
- type: 'lpuart'
- mode: 'freertos'
- custom_name_enabled: 'false'
- type_id: 'lpuart_2.8.1'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LPUART0'
- config_sets:
  - fsl_lpuart_freertos:
    - lpuart_rtos_configuration:
      - clockSource: 'LpuartClock'
      - srcclk: 'ClocksTool_DefaultInit'
      - baudrate: '115200'
      - parity: 'kLPUART_ParityDisabled'
      - stopbits: 'kLPUART_OneStopBit'
      - buffer_size: '128'
      - enableRxRTS: 'false'
      - enableTxCTS: 'false'
      - txCtsSource: 'kLPUART_CtsSourcePin'
      - txCtsConfig: 'kLPUART_CtsSampleAtStart'
      - rx_timeout_constant_ms: '0'
      - rx_timeout_multiplier_ms: '0'
      - tx_timeout_constant_ms: '0'
      - tx_timeout_multiplier_ms: '0'
    - interrupt_rx_tx:
      - IRQn: 'LPUART0_IRQn'
      - enable_priority: 'true'
      - priority: '7'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
lpuart_rtos_handle_t LPUART0_rtos_handle;
lpuart_handle_t LPUART0_lpuart_handle;
uint8_t LPUART0_background_buffer[LPUART0_BACKGROUND_BUFFER_SIZE];
lpuart_rtos_config_t LPUART0_rtos_config = {
  .base = LPUART0_PERIPHERAL,
  .baudrate = 115200UL,
  .srcclk = 96000000UL,
  .parity = kLPUART_ParityDisabled,
  .stopbits = kLPUART_OneStopBit,
  .buffer = LPUART0_background_buffer,
  .buffer_size = LPUART0_BACKGROUND_BUFFER_SIZE,
  .enableRxRTS = false,
  .enableTxCTS = false,
  .txCtsSource = kLPUART_CtsSourcePin,
  .txCtsConfig = kLPUART_CtsSampleAtStart,
  .rx_timeout_constant_ms = 0UL,
  .rx_timeout_multiplier_ms = 0UL,
  .tx_timeout_constant_ms = 0UL,
  .tx_timeout_multiplier_ms = 0UL,
};

static void LPUART0_init(void) {
  /* LPUART rtos initialization */
  LPUART_RTOS_Init(&LPUART0_rtos_handle, &LPUART0_lpuart_handle, &LPUART0_rtos_config);
  /* Interrupt vector LPUART0_IRQn priority settings in the NVIC. */
  NVIC_SetPriority(LPUART0_IRQN, LPUART0_IRQ_PRIORITY);
}

/***********************************************************************************************************************
 * GPIOA initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'GPIOA'
- type: 'gpio'
- mode: 'GPIO'
- custom_name_enabled: 'false'
- type_id: 'gpio_2.7.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'GPIOA'
- config_sets:
  - fsl_gpio:
    - enable_irq: 'false'
    - port_interrupt:
      - IRQn: 'PORTA_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

static void GPIOA_init(void) {
  /* Make sure, the clock gate for port A is enabled (e. g. in pin_mux.c) */
}

/***********************************************************************************************************************
 * I2C0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'I2C0'
- type: 'i2c'
- mode: 'freertos'
- custom_name_enabled: 'false'
- type_id: 'i2c_2.0.5'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'I2C0'
- config_sets:
  - fsl_i2c:
    - i2c_mode: 'kI2C_Master'
    - clockSource: 'BusInterfaceClock'
    - clockSourceFreq: 'GetFreq'
    - rtos_handle:
      - enable_custom_name: 'false'
    - i2c_master_config:
      - enableMaster: 'true'
      - enableStopHold: 'false'
      - baudRate_Bps: '100000'
      - glitchFilterWidth: '0'
    - interrupt_priority:
      - IRQn: 'I2C0_IRQn'
      - enable_priority: 'true'
      - priority: '7'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
i2c_rtos_handle_t I2C0_rtosHandle;
const i2c_master_config_t I2C0_config = {
  .enableMaster = true,
  .enableStopHold = false,
  .baudRate_Bps = 100000UL,
  .glitchFilterWidth = 0U
};

static void I2C0_init(void) {
  /* Initialization function */
  I2C_RTOS_Init(&I2C0_rtosHandle, I2C0_PERIPHERAL, &I2C0_config, I2C0_CLK_FREQ);
  /* Interrupt vector I2C0_IRQn priority settings in the NVIC. */
  NVIC_SetPriority(I2C0_IRQN, I2C0_IRQ_PRIORITY);
}

/***********************************************************************************************************************
 * UART0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'UART0'
- type: 'uart'
- mode: 'freertos'
- custom_name_enabled: 'false'
- type_id: 'uart_2.5.1'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'UART0'
- config_sets:
  - fsl_uart_freertos:
    - uart_rtos_configuration:
      - clockSource: 'BusInterfaceClock'
      - clockSourceFreq: 'GetFreq'
      - baudrate: '115200'
      - parity: 'kUART_ParityDisabled'
      - stopbits: 'kUART_OneStopBit'
      - buffer_size: '32'
    - interrupt_rx_tx:
      - IRQn: 'UART0_RX_TX_IRQn'
      - enable_priority: 'true'
      - priority: '7'
    - interrupt_err:
      - IRQn: 'UART0_ERR_IRQn'
      - enable_priority: 'true'
      - priority: '7'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
uart_rtos_handle_t UART0_rtos_handle;
uart_handle_t UART0_uart_handle;
uint8_t UART0_background_buffer[UART0_BACKGROUND_BUFFER_SIZE];
uart_rtos_config_t UART0_rtos_config = {
  .base = UART0_PERIPHERAL,
  .baudrate = 115200UL,
  .parity = kUART_ParityDisabled,
  .stopbits = kUART_OneStopBit,
  .buffer = UART0_background_buffer,
  .buffer_size = UART0_BACKGROUND_BUFFER_SIZE
};

static void UART0_init(void) {
  /* UART clock source initialization */
  UART0_rtos_config.srcclk = UART0_CLOCK_SOURCE;
  /* UART rtos initialization */
  UART_RTOS_Init(&UART0_rtos_handle, &UART0_uart_handle, &UART0_rtos_config);
  /* Interrupt vector UART0_RX_TX_IRQn priority settings in the NVIC. */
  NVIC_SetPriority(UART0_SERIAL_RX_TX_IRQN, UART0_SERIAL_RX_TX_IRQ_PRIORITY);
  /* Interrupt vector UART0_ERR_IRQn priority settings in the NVIC. */
  NVIC_SetPriority(UART0_SERIAL_ERROR_IRQN, UART0_SERIAL_ERROR_IRQ_PRIORITY);
}

/***********************************************************************************************************************
 * GPIOD initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'GPIOD'
- type: 'gpio'
- mode: 'GPIO'
- custom_name_enabled: 'false'
- type_id: 'gpio_2.7.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'GPIOD'
- config_sets:
  - fsl_gpio:
    - enable_irq: 'true'
    - port_interrupt:
      - IRQn: 'PORTD_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'true'
      - priority: '7'
      - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

static void GPIOD_init(void) {
  /* Make sure, the clock gate for port D is enabled (e. g. in pin_mux.c) */
  /* Interrupt vector PORTD_IRQn priority settings in the NVIC. */
  NVIC_SetPriority(GPIOD_IRQN, GPIOD_IRQ_PRIORITY);
  /* Enable interrupt GPIOD_IRQN request in the NVIC */
  EnableIRQ(GPIOD_IRQN);
}

/***********************************************************************************************************************
 * UART2 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'UART2'
- type: 'uart'
- mode: 'freertos'
- custom_name_enabled: 'false'
- type_id: 'uart_2.5.1'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'UART2'
- config_sets:
  - fsl_uart_freertos:
    - uart_rtos_configuration:
      - clockSource: 'BusInterfaceClock'
      - clockSourceFreq: 'GetFreq'
      - baudrate: '115200'
      - parity: 'kUART_ParityDisabled'
      - stopbits: 'kUART_OneStopBit'
      - buffer_size: '128'
    - interrupt_rx_tx:
      - IRQn: 'UART2_RX_TX_IRQn'
      - enable_priority: 'true'
      - priority: '6'
    - interrupt_err:
      - IRQn: 'UART2_ERR_IRQn'
      - enable_priority: 'true'
      - priority: '7'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
uart_rtos_handle_t UART2_rtos_handle;
uart_handle_t UART2_uart_handle;
uint8_t UART2_background_buffer[UART2_BACKGROUND_BUFFER_SIZE];
uart_rtos_config_t UART2_rtos_config = {
  .base = UART2_PERIPHERAL,
  .baudrate = 115200UL,
  .parity = kUART_ParityDisabled,
  .stopbits = kUART_OneStopBit,
  .buffer = UART2_background_buffer,
  .buffer_size = UART2_BACKGROUND_BUFFER_SIZE
};

static void UART2_init(void) {
  /* UART clock source initialization */
  UART2_rtos_config.srcclk = UART2_CLOCK_SOURCE;
  /* UART rtos initialization */
  UART_RTOS_Init(&UART2_rtos_handle, &UART2_uart_handle, &UART2_rtos_config);
  /* Interrupt vector UART2_RX_TX_IRQn priority settings in the NVIC. */
  NVIC_SetPriority(UART2_SERIAL_RX_TX_IRQN, UART2_SERIAL_RX_TX_IRQ_PRIORITY);
  /* Interrupt vector UART2_ERR_IRQn priority settings in the NVIC. */
  NVIC_SetPriority(UART2_SERIAL_ERROR_IRQN, UART2_SERIAL_ERROR_IRQ_PRIORITY);
}

/***********************************************************************************************************************
 * FATFS initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'FATFS'
- type: 'fatfs'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'fatfs_0.14.0'
- functional_group: 'BOARD_InitPeripherals'
- config_sets:
  - init_config:
    - initConfig:
      - initPartitionsStr: 'false'
      - multiplePartitions:
        - 0:
          - Volume: '0'
          - Partition: 'autoDetect'
        - 1:
          - Volume: '0'
          - Partition: 'autoDetect'
      - enablePhysicalLayerInit: 'false'
      - diskConfig:
        - initFunctionID: 'FATFS_DiskInit'
      - initResultObject: 'false'
      - resultName: 'FATFS_Result'
      - fatfsObjects:
        - 0:
          - objID: 'FATFS_System_0'
          - diskMount: 'false'
          - mountPath: '0:'
          - mountInitOpt: 'false'
      - filObjects: []
      - filInfoObjects: []
      - dirObjects: []
  - ff_config:
    - revisionID: 'rev15_0'
    - MSDKadaptation: 'SDSPI_DISK_ENABLE'
    - functionConfig:
      - FF_FS_READONLY: 'false'
      - FF_FS_MINIMIZE: 'level1'
      - FF_USE_FIND: 'disableDirRead'
      - FF_USE_MKFS: 'true'
      - FF_USE_FASTSEEK: 'false'
      - FF_USE_EXPAND: 'false'
      - FF_USE_CHMOD: 'false'
      - FF_USE_LABEL: 'false'
      - FF_USE_FORWARD: 'false'
      - FF_USE_STRFUNC: 'enableWithoutConversion'
      - FF_PRINT_LLI: 'true'
      - FF_PRINT_FLOAT: 'enableFloat'
    - namespaceConfig:
      - FF_USE_LFN: 'disableLfn'
      - FF_MAX_LFN: '255'
      - FF_LFN_BUF: 'LFNID'
      - FF_SFN_BUF: 'SFNID'
      - FF_LFN_UNICODE: 'UTF16'
      - FF_STRF_ENCODE: 'UTF8'
      - FF_CODE_PAGE: 'cpUS'
      - FF_FS_RPATH: 'enableRP2'
    - driveConfig:
      - FF_VOLUMES: '6'
      - FF_STR_VOLUME_ID: 'numericId'
      - volumes:
        - 0:
          - volumeStr: 'RAM'
        - 1:
          - volumeStr: 'NAND'
        - 2:
          - volumeStr: 'CF'
        - 3:
          - volumeStr: 'SD'
        - 4:
          - volumeStr: 'SD2'
        - 5:
          - volumeStr: 'USB'
      - FF_MULTI_PARTITION: 'false'
      - FF_MIN_SS: 'value512'
      - FF_MAX_SS: 'value512'
      - FF_LBA64: 'false'
      - FF_MIN_GPT: '0x10000000'
      - FF_USE_TRIM: 'false'
    - systemConfig:
      - FF_FS_TINY: 'false'
      - FF_FS_EXFAT: 'false'
      - FF_FS_NORTC: 'false'
      - FF_NORTC_MON: '1'
      - FF_NORTC_MDAY: '1'
      - FF_NORTC_YEAR: '2022'
      - FF_FS_NOFSINFO: ''
      - FF_FS_LOCK: '0'
      - FF_FS_REENTRANT: 'false'
      - FF_FS_TIMEOUT: '1000'
    - fatfs_codegenerator: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
/* FATFS System object */
FATFS FATFS_System_0;

/* Empty initialization function (commented out)
static void FATFS_init(void) {
} */

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
void BOARD_InitPeripherals(void)
{
  /* Initialize components */
  UART1_init();
  LPUART0_init();
  GPIOA_init();
  I2C0_init();
  UART0_init();
  GPIOD_init();
  UART2_init();
}

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void)
{
  BOARD_InitPeripherals();
}
