/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_uart.h"
#include "fsl_uart_freertos.h"
#include "fsl_clock.h"
#include "fsl_lpuart.h"
#include "fsl_lpuart_freertos.h"
#include "fsl_gpio.h"
#include "fsl_dspi.h"
#include "fsl_dspi_freertos.h"
#include "ff.h"
#include "diskio.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* Definition of peripheral ID */
#define UART1_PERIPHERAL UART1
/* Definition of the clock source frequency */
#define UART1_CLOCK_SOURCE CLOCK_GetFreq(UART1_CLK_SRC)
/* Definition of the backround buffer size */
#define UART1_BACKGROUND_BUFFER_SIZE 32
/* UART1 interrupt vector ID (number). */
#define UART1_SERIAL_RX_TX_IRQN UART1_RX_TX_IRQn
/* UART1 interrupt vector priority. */
#define UART1_SERIAL_RX_TX_IRQ_PRIORITY 7
/* UART1 interrupt vector ID (number). */
#define UART1_SERIAL_ERROR_IRQN UART1_ERR_IRQn
/* UART1 interrupt vector priority. */
#define UART1_SERIAL_ERROR_IRQ_PRIORITY 7
/* Definition of peripheral ID */
#define LPUART0_PERIPHERAL LPUART0
/* Definition of the backround buffer size */
#define LPUART0_BACKGROUND_BUFFER_SIZE 128
/* LPUART0 interrupt vector ID (number). */
#define LPUART0_IRQN LPUART0_IRQn
/* LPUART0 interrupt vector priority. */
#define LPUART0_IRQ_PRIORITY 7
/* Alias for GPIOA peripheral */
#define GPIOA_GPIO GPIOA
/* BOARD_InitPeripherals defines for SPI0 */
/* Definition of peripheral ID */
#define SPI0_PERIPHERAL SPI0
/* Definition of the clock source */
#define SPI0_CLOCK_SOURCE DSPI0_CLK_SRC
/* Definition of the clock source frequency */
#define SPI0_CLK_FREQ CLOCK_GetFreq(SPI0_CLOCK_SOURCE)
/* SPI0 interrupt vector ID (number). */
#define SPI0_IRQN SPI0_IRQn
/* SPI0 interrupt vector priority. */
#define SPI0_IRQ_PRIORITY 8

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern uart_rtos_handle_t UART1_rtos_handle;
extern uart_handle_t UART1_uart_handle;
extern uart_rtos_config_t UART1_rtos_config;
extern lpuart_rtos_handle_t LPUART0_rtos_handle;
extern lpuart_handle_t LPUART0_lpuart_handle;
extern lpuart_rtos_config_t LPUART0_rtos_config;
extern dspi_rtos_handle_t SPI0_rtosHandle;
extern const dspi_master_config_t SPI0_config;
/* FATFS System object */
extern FATFS FATFS_System_0;

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
