/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_uart.h"
#include "fsl_uart_freertos.h"
#include "fsl_clock.h"
#include "fsl_lpuart.h"
#include "fsl_lpuart_freertos.h"
#include "fsl_gpio.h"
#include "fsl_i2c.h"
#include "fsl_i2c_freertos.h"
#include "ff.h"
#include "diskio.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* Definition of peripheral ID */
#define UART1_PERIPHERAL UART1
/* Definition of the clock source frequency */
#define UART1_CLOCK_SOURCE CLOCK_GetFreq(UART1_CLK_SRC)
/* Definition of the backround buffer size */
#define UART1_BACKGROUND_BUFFER_SIZE 32
/* UART1 interrupt vector ID (number). */
#define UART1_SERIAL_RX_TX_IRQN UART1_RX_TX_IRQn
/* UART1 interrupt vector priority. */
#define UART1_SERIAL_RX_TX_IRQ_PRIORITY 7
/* UART1 interrupt vector ID (number). */
#define UART1_SERIAL_ERROR_IRQN UART1_ERR_IRQn
/* UART1 interrupt vector priority. */
#define UART1_SERIAL_ERROR_IRQ_PRIORITY 7
/* Definition of peripheral ID */
#define LPUART0_PERIPHERAL LPUART0
/* Definition of the backround buffer size */
#define LPUART0_BACKGROUND_BUFFER_SIZE 128
/* LPUART0 interrupt vector ID (number). */
#define LPUART0_IRQN LPUART0_IRQn
/* LPUART0 interrupt vector priority. */
#define LPUART0_IRQ_PRIORITY 7
/* Alias for GPIOA peripheral */
#define GPIOA_GPIO GPIOA
/* BOARD_InitPeripherals defines for I2C0 */
/* Definition of peripheral ID */
#define I2C0_PERIPHERAL I2C0
/* Definition of the clock source */
#define I2C0_CLOCK_SOURCE I2C0_CLK_SRC
/* Definition of the clock source frequency */
#define I2C0_CLK_FREQ CLOCK_GetFreq(I2C0_CLOCK_SOURCE)
/* I2C0 interrupt vector ID (number). */
#define I2C0_IRQN I2C0_IRQn
/* I2C0 interrupt vector priority. */
#define I2C0_IRQ_PRIORITY 7
/* Definition of peripheral ID */
#define UART0_PERIPHERAL UART0
/* Definition of the clock source frequency */
#define UART0_CLOCK_SOURCE CLOCK_GetFreq(UART0_CLK_SRC)
/* Definition of the backround buffer size */
#define UART0_BACKGROUND_BUFFER_SIZE 32
/* UART0 interrupt vector ID (number). */
#define UART0_SERIAL_RX_TX_IRQN UART0_RX_TX_IRQn
/* UART0 interrupt vector priority. */
#define UART0_SERIAL_RX_TX_IRQ_PRIORITY 7
/* UART0 interrupt vector ID (number). */
#define UART0_SERIAL_ERROR_IRQN UART0_ERR_IRQn
/* UART0 interrupt vector priority. */
#define UART0_SERIAL_ERROR_IRQ_PRIORITY 7
/* Alias for GPIOD peripheral */
#define GPIOD_GPIO GPIOD
/* Alias for PORTD */
#define GPIOD_PORT PORTD
/* GPIOD interrupt vector ID (number). */
#define GPIOD_IRQN PORTD_IRQn
/* GPIOD interrupt vector priority. */
#define GPIOD_IRQ_PRIORITY 7
/* GPIOD interrupt handler identifier. */
#define GPIOD_IRQHANDLER PORTD_IRQHandler
/* Definition of peripheral ID */
#define UART2_PERIPHERAL UART2
/* Definition of the clock source frequency */
#define UART2_CLOCK_SOURCE CLOCK_GetFreq(UART2_CLK_SRC)
/* Definition of the backround buffer size */
#define UART2_BACKGROUND_BUFFER_SIZE 128
/* UART2 interrupt vector ID (number). */
#define UART2_SERIAL_RX_TX_IRQN UART2_RX_TX_IRQn
/* UART2 interrupt vector priority. */
#define UART2_SERIAL_RX_TX_IRQ_PRIORITY 6
/* UART2 interrupt vector ID (number). */
#define UART2_SERIAL_ERROR_IRQN UART2_ERR_IRQn
/* UART2 interrupt vector priority. */
#define UART2_SERIAL_ERROR_IRQ_PRIORITY 7

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern uart_rtos_handle_t UART1_rtos_handle;
extern uart_handle_t UART1_uart_handle;
extern uart_rtos_config_t UART1_rtos_config;
extern lpuart_rtos_handle_t LPUART0_rtos_handle;
extern lpuart_handle_t LPUART0_lpuart_handle;
extern lpuart_rtos_config_t LPUART0_rtos_config;
extern i2c_rtos_handle_t I2C0_rtosHandle;
extern const i2c_master_config_t I2C0_config;
extern uart_rtos_handle_t UART0_rtos_handle;
extern uart_handle_t UART0_uart_handle;
extern uart_rtos_config_t UART0_rtos_config;
extern uart_rtos_handle_t UART2_rtos_handle;
extern uart_handle_t UART2_uart_handle;
extern uart_rtos_config_t UART2_rtos_config;
/* FATFS System object */
extern FATFS FATFS_System_0;

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
