/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define SOPT5_UART0TXSRC_UART_TX 0x00u /*!<@brief UART 0 transmit data source select: UART0_TX pin */
#define SOPT5_UART1TXSRC_UART_TX 0x00u /*!<@brief UART 1 transmit data source select: UART1_TX pin */

/*! @name PORTE0 (number 1), UART1_TX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_UART1_TX_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_UART1_TX_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_UART1_TX_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTE1 (number 2), UART1_RX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_UART1_RX_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_UART1_RX_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_UART1_RX_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTD0 (number 57), PTD0
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_PTD0_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_PTD0_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_PTD0_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORTB19 (number 42), GPIOB19
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_GPIOB19_GPIO GPIOB                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_GPIOB19_GPIO_PIN_MASK (1U << 19U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_GPIOB19_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_GPIOB19_PIN 19U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_GPIOB19_PIN_MASK (1U << 19U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTD5 (number 62), GPIOD5
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_GPIOD5_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_GPIOD5_GPIO_PIN_MASK (1U << 5U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_GPIOD5_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_GPIOD5_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_GPIOD5_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORTD4 (number 61), GPIOD4
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_GPIOD4_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_GPIOD4_GPIO_PIN_MASK (1U << 4U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_GPIOD4_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_GPIOD4_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_GPIOD4_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
